export const filterLaptop = [
  {
    title: "Thương hiệu",
    list: [
      "Lenovo",
      "Razer",
      "Dell",
      "Asus",
      "Acer",
      "HP",
      "Microsoft",
      "Apple",
    ],
    filter: "trademark",
  },
  {
    title: "RAM",
    list: [
      "4 GB",
      "8 GB",
      "12 GB",
      "16 GB",
      "20 GB",
      "32 GB",
      "64 GB",
      "128 GB",
    ],
    filter: "RAM",
  },
  {
    title: "CPU",
    list: [
      "Intel Dual Core",
      "Intel Core i3",
      "Intel Core i5",
      "Intel Core i7",
      "Intel Core i9",
      "InTel Xeon",
      "AMD Ryzen 3",
      "AMD Ryzen 5",
      "MD Ryzen 7",
      "Apple M1",
    ],
    filter: "CPU",
  },
  {
    title: "Màn hình",
    list: ["13.3 inch", "14 inch", "15.6 inch"],
    filter: "screenSize",
  },
];
